import type { UploadSource } from "../types";
import { generateId } from "./platform";

/**
 * Normalizes a browser FileList (from `<input type="file">`,
 * `<input type="file" webkitdirectory>`, or `DataTransfer.files`) into
 * a flat list of UploadSource entries.
 *
 * Preserves the relative path so the caller can recreate the folder
 * structure in Drive. The GoogleDriveAdapter is responsible for actually
 * creating nested folders; the engine just keeps the original path with
 * each file.
 *
 * `getId` is injected so tests can produce deterministic ids; defaults
 * to a random uuid.
 */
export function flattenFileList(
  files: FileList | File[] | { name: string; size: number; type?: string; webkitRelativePath?: string; slice: Blob["slice"] }[],
  getId: () => string = generateId
): UploadSource[] {
  const list = Array.from(files as ArrayLike<{ name: string; size: number; type?: string; webkitRelativePath?: string; slice: Blob["slice"] }>);
  return list.map((file) => {
    const rel =
      ("webkitRelativePath" in file && file.webkitRelativePath) ||
      // DataTransferItem.getAsFile() does not carry webkitRelativePath on
      // some browsers; fall back to the bare name.
      file.name;
    return {
      file: file as unknown as Blob,
      relativePath: rel,
      name: file.name,
      size: file.size,
      mimeType: file.type || "application/octet-stream",
      // The id is added by the QueueManager; we just carry the source here.
      // We attach an id through a side-channel so callers can map results.
      // The id is generated by the engine in QueueManager.add; here we
      // simply leave a hint.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      ...({ _hint: getId() } as any),
    };
  });
}

/**
 * Groups a flat list of UploadSource entries by their first path segment.
 * Used by the GoogleDriveAdapter when recursively creating folders.
 */
export function groupByTopLevel(sources: UploadSource[]): Map<string, UploadSource[]> {
  const groups = new Map<string, UploadSource[]>();
  for (const src of sources) {
    const top = src.relativePath.split("/")[0] || src.name || "untitled";
    let bucket = groups.get(top);
    if (!bucket) {
      bucket = [];
      groups.set(top, bucket);
    }
    bucket.push(src);
  }
  return groups;
}
